version: "3.3"
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "10000:10000"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./client:/app
    restart: on-failure
    container_name: client
  api_backend:
    build:
      context: ./api_backend
      dockerfile: Dockerfile
    restart: on-failure
    container_name: api_backend
    volumes:
      - /app/node_modules
      - ./api_backend:/app